---
booktitle: Proceedings of the Fourth International Conference on Automated Machine
  Learning
shortname: AutoML
year: '2025'
volume: '293'
start: &1 2025-09-08
end: 2025-09-11
published: 2025-11-11
conference_number: '4'
layout: proceedings
series: Proceedings of Machine Learning Research
publisher: PMLR
issn: 2640-3498
id: automl2025
month: 0
cycles: false
bibtex_editor: Akoglu, Leman and Doerr, Carola and van Rijn, Jan N. and Garnett, Roman
  and Gardner, Jacob R.
editor:
- given: Leman
  family: Akoglu
- given: Carola
  family: Doerr
- given: Jan N.
  family: Rijn
  prefix: van
- given: Roman
  family: Garnett
- given: Jacob R.
  family: Gardner
title: Proceedings of Machine Learning Research
description: |
  Proceedings of the Fourth International Conference on Automated Machine Learning
    Held in Cornell Tech, New York, NY, USA on 08-11 September 2025

  Published as Volume 293 by the Proceedings of Machine Learning Research on 11 November 2025.

  Volume Edited by:
    Leman Akoglu
    Carola Doerr
    Jan N. van Rijn
    Roman Garnett
    Jacob R. Gardner

  Series Editors:
    Neil D. Lawrence
date_str: '08--11 Sep'
url: https://proceedings.mlr.press
author:
  name: PMLR
baseurl: "/v293"
twitter_username: MLResearchPress
github_username: mlresearch
markdown: kramdown
exclude:
- README.md
- Gemfile
- ".gitignore"
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-remote-theme
remote_theme: mlresearch/jekyll-theme
style: pmlr
permalink: "/:title.html"
ghub:
  edit: true
  repository: v293
display:
  copy_button:
    bibtex: true
    endnote: true
    apa: true
  comments: false
volume_type: Volume
volume_dir: v293
email: ''
conference:
  name: International Conference on Automated Machine Learning
  url: https://2025.automl.cc/
  location: Cornell Tech, New York, NY, USA
  dates:
  - *1
  - 2025-09-09
  - 2025-09-10
  - 2025-09-11
analytics:
  google:
    tracking_id: UA-92432422-1
link_visibility:
  openreview: true
  pdf: true
  supplementary: true
  software: true
  video: true
  arxiv: true
  doi: true
  website: true
orig_bibfile: automl2025_cleaned_clean.bib
# Site settings
# Original source:  automl2025_cleaned_clean.bib
